# Jupyter Book config for developing and testing munchboka-edutools
title: munchboka-edutools
author: Rene Aas
only_build_toc_files: true
execute:
  execute_notebooks: "off"
sphinx:
  extra_extensions:
    - munchboka_edutools
  config:
    html_theme: sphinx_book_theme
    html_static_path: ["_static"]
    html_baseurl: "https://dev.munchboka.no"
    html_theme_options:
      pygments_light_style: "github-light"
      pygments_dark_style: "github-dark-high-contrast"
